reference_jdk: &reference_jdk
  'JDK="adopt@1.11"'
reference_os: &reference_os
  'linux'
language: bash
git:
  depth: false
os:
  - osx
  - windows
  - *reference_os
dist: xenial
env:
  global:
    - TERM=dumb
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
    - PUBLISH="false"
  matrix:
    - *reference_jdk
    - JDK="adopt-openj9@1.11"
    - JDK="adopt-openj9@"
    - JDK="adopt@"
before_install:
  - curl "${GRAVIS}.disable-windows-defender.sh" --output .disable-windows-defender.sh
  - source .disable-windows-defender.sh
  - curl "${GRAVIS}.install-jdk-travis.sh" --output .install-jdk-travis.sh
  - source .install-jdk-travis.sh
script:
  - ./gradlew clean test --parallel
before_cache:
  - curl "${GRAVIS}.clean_gradle_cache.sh" --output .clean_gradle_cache.sh
  - bash .clean_gradle_cache.sh
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
