reference_jdk: &reference_jdk
  'JDK="adopt@1.11"'
reference_os: &reference_os
  'linux'

language: bash

git:
  depth: false

os:
  - osx
  - windows
  - *reference_os

stages:
  - base
  - test

env:
  global:
    - TERM=dumb
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
  matrix:
    - *reference_jdk
    - JDK="adopt-openj9@1.11"
    - JDK="adopt-openj9@"
    - JDK="adopt@"

jobs:
  exclude:
    - stage: test
      os: linux
      env: *reference_jdk
  include:
    - stage: base
      os: linux
      env: *reference_jdk

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk

script:
  - travis_retry ./gradlew check runAll

before_cache:
  - $GRAVIS/clean-gradle-cache

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
